$(function() {
	$('.mission').css({'font-size': (screen.height * 0.099) * 0.333333333});
	$('header').css({height: (screen.height * 0.099)});
	$('header a').css({'font-size': (screen.height * 0.099) * 0.333333333});
	$('header a').css({'margin-top': (screen.height * 0.099) * 0.333333333});
	$('.canvas').css({height: screen.height * 0.75});
	$('.controls').css({height: screen.height * 0.149});
	$('.controls button').css({height: (screen.height * 0.15) * 0.75});
	$('.controls button').css({width: (screen.height * 0.15) * 0.75});
	$('.controls button').css({'margin': (screen.height * 0.15) * 0.120});
	$('.controls button').css({'font-size': (screen.height * 0.15) * 0.25});
	$('.controls .speed').css({height: (screen.height * 0.15) * 0.35});
	$('.controls .speed').css({'margin': (screen.height * 0.15) * 0.25});
	$('.controls .speed').css({'margin-right': 0});
	$('.controls .speed label').css({'font-size': (screen.height * 0.15) * 0.25});
	$('.inputs').css({height: screen.height * 0.7});
	$('.inputs').css({marginTop: -(screen.height * 0.75)});
	$('.inputs input').css({height: (screen.height * 0.7) * 0.07});
	$('.inputs input').css({'font-size': (screen.height * 0.7) * 0.05});
	$('.inputs p').css({'font-size': (screen.height * 0.7) * 0.04});
	$('.inputs span').css({'font-size': (screen.height * 0.7) * 0.05});
	$('.gits span').css({'font-size': (screen.height * 0.7) * 0.05});
	$('.gits').css({marginTop: -(screen.height * 0.05)});
	$('.gits').css({height: screen.height * 0.199});
});